# Generated by Django 5.2.5 on 2025-08-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_date_created_course_date_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
